language: php

php:
  - 5.4
  - 5.5
  - 5.6

matrix:
  include:
    - php: 5.4
      env: DEPENDENCIES='low'

before_script:
  - if [ "$DEPENDENCIES" != "low" ]; then composer update; fi;
  - if [ "$DEPENDENCIES" = "low" ]; then composer update --prefer-lowest; fi;
  - export PATH=vendor/bin:$PATH

script:
  - phpunit -v --coverage-clover=coverage.clover
  - behat -fprogress --strict

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

